document.write('    <nav class="nav-bar-holder">')
document.write('        <div class="nav-bar" id="nav-bar">')
document.write('            <div class="logo-box">')
document.write('                <a href="index.html" class="blog-title ta-c"><img style="vertical-align: top;" alt="logo"')
document.write('                src="../img/builder.jpeg" /></a>')
document.write('            </div>')
document.write('            <div class="nb-a-holder" id="home"><a id="active" class="nb-a ta-c" href="index.html">首页</a></div>')
document.write('            <div class="nb-a-holder"><a id="active" class="nb-a ta-c" href="intro.html">简介</a></div>')
document.write('            <div class="nb-a-holder"><a id="active" class="nb-a ta-c" href="category.html">分类</a></div>')
document.write('            <div class="nb-a-holder"><a id="active" class="nb-a ta-c" href="archive.html">归档</a></div>')
document.write('            <div class="nb-a-holder"><a id="active" class="nb-a ta-c" href="link.html">我的链接</a></div>')
document.write('        </div>')
document.write('        </nav>')
document.write('    <!--mobile 导航栏-->')
document.write('    <nav class="mobile-nav">')
document.write('        <div class="logo-box">')
document.write('            <a href="index.html" class="blog-title ta-c">')
document.write('            <img style="vertical-align: top;" alt="logo"')
document.write('            src="../img/builder.jpeg" /></a>')
document.write('        </div>')
document.write("        <a id='mobile_cate' style='background-image: url('../img/cate.svg')' href='javascript:void(0);'></a>")
document.write('    </nav>')
document.write('    <ul id="nav-m-list">')
document.write('        <li id="cancel-li"><a class="fr" id="cancel" href="javascript:void(0);"></a></li>')
document.write('        <li id="m-img-li">')
document.write('        <img id="m-img" alt="ArbeiterKlassen" src="../img/builder.jpeg">')
document.write('    </li>')
document.write('<li><a class="w-h-100 fl" href="index.html">首页</a></li>')
document.write('<li><a class="w-h-100 fl" href="intro.html">简介</a></li>')
document.write('<li><a class="w-h-100 fl" href="category.html">分类</a></li>')
document.write('<li><a class="w-h-100 fl" href="archive.html">归档</a></li>')
document.write('<li><a class="w-h-100 fl" href="link.html">我的链接</a></li>')
document.write('</ul>')