document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/太阳照常升起.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/mao3.jpeg" alt="" src="../essays_img/mao3.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/太阳照常升起.html">太阳照常升起</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('')
document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="read-number c-999 fl">47</span>')
document.write('                                <span class="coment-number c-999 fl">0</span>')
document.write('                                <span class="article-date c-999">2021-9-9</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')                           
document.write('                        </div>')
document.write('                    </div>')
document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/三篇读后杂记.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/marx1.jpeg" alt="" src="../essays_img/marx1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/三篇读后杂记.html">三篇读后杂记</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                  人类社会的历史自古分为几个阶段：远古时期——原始社会——奴隶社会——封建社会——资本主义社会——现今。')
document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="coment-number c-999 fl">杂记文章</span>')
document.write('                                <span class="article-date c-999">2021-8-27</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')                           
document.write('                        </div>')
document.write('                    </div>')
document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/论中国国家资本.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/marx1.jpeg" alt="" src="../essays_img/marx1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/论中国国家资本.html">论中国国家资本</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                在实质上，则应当指明，在国家垄断资本主义国家这些国有企业表面上是“公有”的，但实质上是垄断资产阶级最大限度地支配社会资本和剥削劳动人民的一种形式，它的活动主要是促进私人垄断资本的运动，保证私人垄断资本获得高额利润。它以低价向私人垄断组织供应商品和劳务，以高价从私人垄断组织购买商品和劳务。它促进国民经济技术水平的提高和部门结构和地区结构的改造，为私人垄断资本的再生产创造有利条件。国家垄断资本是比私人垄断企业更高的、更集中的资本社会化，它在一定程度上更加适应生产社会化发展的要求；但另一方面它的出现和发展也反映了资本主义私人所有制已经过时，这对资本主义制度无疑构成了一种很大的威胁，因而垄断资产阶级又力图限制国有垄断企业的发展，并在条件有利时实行“非国有化”，将国有企业重新改为私营企业。')
document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">政治经济学</span>')
document.write('                                <span class="article-date c-999">2021-8-21</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')
document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/评当前补习班教育问题.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/hengshui1.jpeg" alt="" src="../essays_img/hengshui1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/评当前补习班教育问题.html">评当前补习班教育问题</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                社会上的基础设施——教育，医疗，工业开始过度市场化。失去了国家政府的管控，自由的市场经济——自由的资本主义开始垄断各行各业。抛去网络，医疗，工业，剩下一个教育成为了金融资本的角逐地。')
document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">社会分析</span>')
document.write('                                <span class="article-date c-999">2021-8-19</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')
document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/谈近期的反黑人思潮.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/antiRacism1.jpeg" alt="" src="../essays_img/antiRacism1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/谈近期的反黑人思潮.html">谈近期的反黑人思潮</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                随着我国改革开放的推进，中国的综合国力不断增强；同时，经济实力的不断提高，吸引了一大批外国籍人士来华。2000年之后，随着我国与大量亚非国家共创的“一带一路”建设的不断推进，大批非洲国家人士来华留学经商。大批非洲国家人士——或者直说黑人入境，直接引发了两个问题——怎么安置外国人？怎么指定对外国人的相应政策？')
document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">社会分析</span>')
document.write('                                <span class="article-date c-999">2021-8-17</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')
document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/怎么办（1）.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/mao1.jpeg" alt="" src="../essays_img/mao1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/怎么办（1）.html">怎么办（1）</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                进入20世纪，俄国首先爆发了1917年的十月革命，一声炮响给中国人民带来了马克思主义。紧接着是1915年中国新文化运动向马克思主义的转变和1919年五四运动的爆发，青年学生和工人站在了革命的前线。1921年，中国共产党成立并开始领导中国工人运动。')
document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">行动理论</span>')
document.write('                                <span class="article-date c-999">2021-7-23</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')
document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/谈巴以冲突.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/mao1.jpeg" alt="" src="../essays_img/mao1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/谈巴以冲突.html">谈巴以冲突</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                我们认为，巴以冲突的表面是宗教和民族的历史矛盾，实质是巴以反战的人民和美国以色列大资本家战争贩子的矛盾。是全世界反战的人民，反战的共产主义者同大资本家战争贩子的斗争。')
document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">社会分析</span>')
document.write('                                <span class="article-date c-999">2021-6-29</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')