
document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/太阳照常升起.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/mao3.jpeg" alt="" src="../essays_img/mao3.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/太阳照常升起.html">太阳照常升起</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('')
document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="read-number c-999 fl">47</span>')
document.write('                                <span class="coment-number c-999 fl">0</span>')
document.write('                                <span class="article-date c-999">2021-9-9</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')                           
document.write('                        </div>')
document.write('                    </div>')
    
document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/三篇读后杂记.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/marx1.jpeg" alt="" src="../essays_img/marx1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/三篇读后杂记.html">三篇读后杂记</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                  人类社会的历史自古分为几个阶段：远古时期——原始社会——奴隶社会——封建社会——资本主义社会——现今。')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="coment-number c-999 fl">杂记文章</span>')
document.write('                                <span class="article-date c-999">2021-8-27</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')                           
document.write('                        </div>')
document.write('                    </div>')
    document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/浅谈教育内卷化.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/Involution1.jpeg" alt="" src="../essays_img/Involution1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/浅谈教育内卷化.html">浅谈教育内卷化</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                  	“内卷化”成了一个流行词。在学生群体中，又引申出了“教育内卷化”这一在学生中的具体体现。要谈教育内卷化，就首先要讲清楚什么是内卷化。')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="coment-number c-999 fl">社会分析</span>')
document.write('                                <span class="article-date c-999">2021-8-22</span>')
document.write('                                <span class="article-author one-line-overflow c-999">小蔡鸡</span>')
document.write('                            </span>')                           
document.write('                        </div>')
document.write('                    </div>')

document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/论中国国家资本.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/marx1.jpeg" alt="" src="../essays_img/marx1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/论中国国家资本.html">论中国国家资本</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                在实质上，则应当指明，在国家垄断资本主义国家这些国有企业表面上是“公有”的，但实质上是垄断资产阶级最大限度地支配社会资本和剥削劳动人民的一种形式，它的活动主要是促进私人垄断资本的运动，保证私人垄断资本获得高额利润。它以低价向私人垄断组织供应商品和劳务，以高价从私人垄断组织购买商品和劳务。它促进国民经济技术水平的提高和部门结构和地区结构的改造，为私人垄断资本的再生产创造有利条件。国家垄断资本是比私人垄断企业更高的、更集中的资本社会化，它在一定程度上更加适应生产社会化发展的要求；但另一方面它的出现和发展也反映了资本主义私人所有制已经过时，这对资本主义制度无疑构成了一种很大的威胁，因而垄断资产阶级又力图限制国有垄断企业的发展，并在条件有利时实行“非国有化”，将国有企业重新改为私营企业。')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">政治经济学</span>')
document.write('                                <span class="article-date c-999">2021-8-21</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')

document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/简单论述近两年中国国内爆发式出现的民族主义.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/leninism1.jpeg" alt="" src="../essays_img/leninism1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/简单论述近两年中国国内爆发式出现的民族主义.html">简单论述近两年中国国内爆发式出现的民族主义</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                梁启超是中国揭示和宣传近代民族主义的第一人。（1902年）他发表《论民族竞争之大势》，明确提出：“今日欲救中国，无他术焉，亦先建设一民族主义国家而已。”')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">社会分析</span>')
document.write('                                <span class="article-date c-999">2021-8-21</span>')
document.write('                                <span class="article-author one-line-overflow c-999">有为青年</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')

document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/评当前补习班教育问题.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/hengshui1.jpeg" alt="" src="../essays_img/hengshui1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/评当前补习班教育问题.html">评当前补习班教育问题</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                社会上的基础设施——教育，医疗，工业开始过度市场化。失去了国家政府的管控，自由的市场经济——自由的资本主义开始垄断各行各业。抛去网络，医疗，工业，剩下一个教育成为了金融资本的角逐地。')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">社会分析</span>')
document.write('                                <span class="article-date c-999">2021-8-19</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')

document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/谈近期的反黑人思潮.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/antiRacism1.jpeg" alt="" src="../essays_img/antiRacism1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/谈近期的反黑人思潮.html">谈近期的反黑人思潮</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                随着我国改革开放的推进，中国的综合国力不断增强；同时，经济实力的不断提高，吸引了一大批外国籍人士来华。2000年之后，随着我国与大量亚非国家共创的“一带一路”建设的不断推进，大批非洲国家人士来华留学经商。大批非洲国家人士——或者直说黑人入境，直接引发了两个问题——怎么安置外国人？怎么指定对外国人的相应政策？')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">社会分析</span>')
document.write('                                <span class="article-date c-999">2021-8-17</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')

document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/怎么办（1）.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/mao1.jpeg" alt="" src="../essays_img/mao1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/怎么办（1）.html">怎么办（1）</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                进入20世纪，俄国首先爆发了1917年的十月革命，一声炮响给中国人民带来了马克思主义。紧接着是1915年中国新文化运动向马克思主义的转变和1919年五四运动的爆发，青年学生和工人站在了革命的前线。1921年，中国共产党成立并开始领导中国工人运动。')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">行动理论</span>')
document.write('                                <span class="article-date c-999">2021-7-23</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')

document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/谈巴以冲突.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/mao1.jpeg" alt="" src="../essays_img/mao1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/谈巴以冲突.html">谈巴以冲突</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                我们认为，巴以冲突的表面是宗教和民族的历史矛盾，实质是巴以反战的人民和美国以色列大资本家战争贩子的矛盾。是全世界反战的人民，反战的共产主义者同大资本家战争贩子的斗争。')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">社会分析</span>')
document.write('                                <span class="article-date c-999">2021-6-29</span>')
document.write('                                <span class="article-author one-line-overflow c-999">ArbeiterKlassen</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')

document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/论信息化资本主义.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/marx1.jpeg" alt="" src="../essays_img/marx1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/论信息化资本主义.html">论信息化资本主义</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                自20世纪40至50年代起，电子计算——即后来的计算机的兴起促使社会生产力大幅提高。90年代后互联网在全球普及，美国的苹果、微软等公司腾飞；随之而来的Twitter,Facebook,Youtube等社交视频网站开始在网民中得到信任和推广，成为全球性的社交网站。')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">政治经济学</span>')
document.write('                                <span class="article-date c-999">2021-5-6</span>')
document.write('                                <span class="article-author one-line-overflow c-999">Fashiung</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')

document.write('                    <div class="article-box">')
document.write('                        <div class="ab-content">')
document.write('                            <a href="../articles/中产阶级扩大论.html" class="article-img-box">')
document.write('                                <img class="lazy-image article-img" data-src="../essays_img/marx1.jpeg" alt="" src="../essays_img/marx1.jpeg">')
document.write('                            </a>')
document.write('                            <div class="article-title">')
document.write('                                <a href="../articles/中产阶级扩大论.html">中产阶级扩大论</a>')
document.write('                            </div>')
document.write('                            <div class="article-detail-box c-666">')
document.write('                                马克思主义论述：中产阶级，即小资产阶级实际上是无产阶级中的特殊组成部分，占有少部分的生产资料，但不属于大资产阶级。既可以单独作为社会阶级之一，也可以划分进无产阶级之内。')
document.write('      中产阶级，中产阶层，小资产阶级等词汇同义。')
document.write('      本文部分观点和论述来源：')
document.write('      1975.11月刊《红旗》杂志发表的《请看苏修的新玩意儿》')
document.write('      Faschiung-《论信息化资本主义》')

document.write('                            </div>')
document.write('                            <span class="article-tail-box">')
document.write('                                <span class="comment-number c-999 fl">社会分析</span>')
document.write('                                <span class="article-date c-999">2021-3-13</span>')
document.write('                                <span class="article-author one-line-overflow c-999">Faschiung</span>')
document.write('                            </span>')
document.write('                        </div>')
document.write('                    </div>')